services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-ssl-${ENVIRONMENT}
    volumes:
      - ./conf.d/${ENVIRONMENT}/:/etc/nginx/conf.d/:ro
      - ./certs/self-signed:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./data:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - web-network
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  certbot:
    image: certbot/certbot
    container_name: certbot-${ENVIRONMENT}
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./data:/etc/letsencrypt
    networks:
      - web-network

networks:
  web-network:
    driver: bridge